[package]
name = "flannel-cni"
description = "flannel CNI plugin library (delegates to bridge/host-local)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
flannel-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
netns-rs.workspace = true
